# Generated by Django 4.0.3 on 2022-03-26 02:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('brand', models.CharField(max_length=150)),
                ('product_name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('website_link', models.CharField(max_length=150)),
                ('tags', models.CharField(max_length=150)),
                ('image_link', models.CharField(max_length=1000)),
                ('product_description', models.CharField(max_length=4000)),
                ('product_type', models.CharField(max_length=150)),
                ('favorites', models.ManyToManyField(blank=True, default=None, related_name='favorite', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
