# Generated by Django 4.0.3 on 2022-03-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('hex_value', models.CharField(blank=True, max_length=7, null=True)),
                ('colour_name', models.CharField(blank=True, max_length=150, null=True)),
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'color',
                'managed': False,
            },
        ),
    ]
