# Generated by Django 4.0.3 on 2022-03-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_product_table_productfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfavorite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
