# Generated by Django 4.0.3 on 2022-03-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_productfavorite_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='look',
            name='products',
        ),
    ]
